### ISSUE TITLE
Catarse

### ISSUE THREAD

**Issue by gregmolnar** [opensourcerails/opensourcerails#60] opened 2013-02-17 23:22 UTC
I'd like to submit 3 nice opensource project:
Discourse: http://www.discourse.org/
Catarse: https://github.com/danielweinmann/catarse
Selfstarter: http://selfstarter.us/

**Comment by mbajur** [comment] 2015-08-05 11:17
While the other two are already here, let's convert it to **catarse** request.

https://github.com/catarse/catarse

**Comment by mbajur** [comment] 2015-08-10 21:17
Actually it's a duplicate of #4

**Closed by mbajur** 2015-08-10 21:17 UTC
Labels: Nominated
