### ISSUE TITLE
Snippet-Monkey(http://www.snippet-monkey.com/)

### ISSUE THREAD

**Issue by kannancet** [opensourcerails/opensourcerails#63] opened 2013-02-27 07:10 UTC
Snippet-Monkey helps developers to store their URLs, Code snippets etc online and access, search and use them quickly.
Snippet-Monkey helps developers watch videos, articles and news related to tech world.

Have you ever thought? oh! I had solved this issue before using a blog but can't find it again :(  Don't worry, start using Snippet Monkey to back up your resource URLs here for future development. You can search and find or share it with your friends when you come across the same issue again.

Snippet was created by Snippet-Team. The source is available as open-source in Github.
Features:
=> Save URLs and Snippets, Blogs.
=> Search Your Resources from your "Monkey-Space".
=> Access your resources "Anywhere, AnyTime".
=> Bookmarking made online! Experience platform, machine, place and browser independent bookmarking.
=> Share Your Resources on all Social Networks.
=> Watch Today's Special. Daily tech news, videos and articles promoted by our Team.
=> Exclusive and interesting videos, news, articles from tech world in Tech News Pool.
=> Access Resources Anywhere & Anytime.

**Comment by mbajur** [comment] 2015-08-06 06:15
Duplicate of #61

**Closed by mbajur** 2015-08-06 06:15 UTC
