### ISSUE TITLE
Huginn

### ISSUE THREAD

**Issue by cantino** [opensourcerails/opensourcerails#137] opened 2015-05-03 19:30 UTC
Huginn is a system for building agents that perform automated tasks for you online. They can read the web, watch for events, and take actions on your behalf. Huginn's Agents create and consume events, propagating them along a directed graph. Think of it as a hackable Yahoo! Pipes plus IFTTT on your own server. You always know who has your data. You do.

https://github.com/cantino/huginn

**Comment by mbajur** [comment] 2015-08-05 10:27
Duplicate of https://github.com/opensourcerails/opensourcerails/issues/67

**Closed by mbajur** 2015-08-05 10:27 UTC
