### ISSUE TITLE
DuckRails

### ISSUE THREAD

**Issue by iridakos** [opensourcerails/opensourcerails#199] opened 2016-04-08 23:43 UTC
[DuckRails](https://github.com/iridakos/duckrails) is an open source development tool for mocking API endpoints quickly & dynamically.

**Comment by mbajur** [comment] 2016-04-09 07:14
Duplicate of #194

**Closed by mbajur** 2016-04-09 07:14 UTC

**Comment by iridakos** [comment] 2016-04-09 08:36
Sorry! I didn't see that.
