### ISSUE TITLE
canvas-lms

### ISSUE THREAD

**Issue by lethalbrains** [opensourcerails/opensourcerails#110] opened 2014-07-17 04:50 UTC
Description of Project

https://github.com/instructure/canvas-lms

**Comment by w0www** [comment] 2015-07-28 12:59
n1 project

**Comment by mbajur** [comment] 2015-08-05 11:11
Can you provide any screenshots of that app?

**Comment by mbajur** [comment] 2015-08-05 11:19
Duplicate of #7

**Closed by mbajur** 2015-08-05 11:19 UTC
